apiVersion: apps/v1
kind: Deployment
metadata:
  name: saasproject-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      class: sdev372
  template:
    metadata:
      labels:
        class: sdev372
    spec:
      containers:
        - name: saasproject-container
          image: deebrecke/saasgames
          ports:
            - containerPort: 8080